### ISSUE TITLE
BRA_CAX bug

### ISSUE THREAD

**Issue by vflo** [sapfluxnet/sapfluxnetQC1#43]
Process of BRA_CAX generates two main bugs:

1. repeated solarTIMESTAMPS
1. Dont generate sfn_data objects when no sapwood metadata is present

**Comment by MalditoBarbudo** [comment]
1. repeated solarTIMESTAMPs

This is due to repeated TIMESTAMPs in the original environmental data. But is a hideous one, TIMESTAMPs of environmental data are repeated but with 0.0004 seconds delay, so they not appear in the QC1 tests as repeated.
There is no solution from the sapfluxnetQC1 point of view, as the data set must be resetted to origin, fixed in the template and resubmitted.

**Comment by MalditoBarbudo** [comment]
2. Dont generate sfn_data objects when no sapwood metadata is present
This is a bug in `sapfluxnetQC1`, as there was no contingency plan in the function algorithm to completly
lack of sapwood metadata. Working on it to fix it as soon as possible.
